import type { Metadata } from "next";
import { Lato, League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@cruzco/components/header";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-lato",
  display: "swap",
});

const league_Spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-domine",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${league_Spartan.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
